Skip to content
zacharee
/
RootActivityLauncher
Public
Code
Issues
2
Pull requests
Actions
Projects
Security
Insights
RootActivityLauncher/app/build.gradle
@zacharee
zacharee Version 25
 1 contributor
86 lines (71 sloc)  3.1 KB
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdkVersion 33

    defaultConfig {
        applicationId "tk.zwander.rootactivitylauncher"
        namespace = "tk.zwander.rootactivitylauncher"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 25
        versionName versionCode.toString()
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }

    buildFeatures {
        viewBinding = true
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.4.0-alpha02"
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:atomicfu:0.18.5'

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'androidx.preference:preference-ktx:1.2.0'

    implementation "androidx.compose.material3:material3:1.1.0-alpha03"
    implementation 'androidx.compose.ui:ui-tooling-preview:1.4.0-alpha03'
    implementation 'androidx.compose.runtime:runtime:1.4.0-alpha03'
    implementation "androidx.compose.material:material:1.4.0-alpha03"
    implementation 'androidx.activity:activity-compose:1.6.1'
    implementation "com.google.android.material:compose-theme-adapter-3:1.1.1"
    implementation 'com.google.accompanist:accompanist-themeadapter-material3:0.28.0'

    implementation("io.coil-kt:coil:2.2.2")
    implementation("io.coil-kt:coil-compose:2.2.2")
    implementation "com.github.skgmn:composetooltip:0.2.0"

    implementation 'com.google.android.material:material:1.7.0'
    implementation 'com.google.code.gson:gson:2.10'
    implementation 'com.google.firebase:firebase-crashlytics:18.3.2'
    //Crashlytics doesn't seem to work without this added (wtf)
    implementation 'com.google.firebase:firebase-analytics:21.2.0'

    implementation "dev.rikka.shizuku:api:12.2.0"
    implementation "dev.rikka.shizuku:provider:12.2.0"
    implementation 'org.lsposed.hiddenapibypass:hiddenapibypass:4.3'
    implementation 'com.github.zacharee:PatreonSupportersRetrieval:8436bbdbdc'
    implementation 'com.joaomgcd:taskerpluginlibrary:0.4.7'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
    implementation 'com.github.Chainfire:libsuperuser:1.1.0.201907261845'
    implementation 'com.github.2hamed:ProgressCircula:0.2.1'

    debugImplementation 'androidx.compose.ui:ui-tooling:1.3.2'
}
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
RootActivityLauncher/build.gradle at 5677247839c3520d52999e12f36b6dde20afa31f · zacharee/RootActivityLauncher
